### ISSUE TITLE
Running Error. it seems lack ./data-bin/train-obj.h5py file

### ISSUE THREAD

**Issue by JingyuLi-code** [LibertFan/TCIC#1]
![image](https://user-images.githubusercontent.com/45377489/125149628-ab349680-e16c-11eb-95e5-4f1ba8f324fd.png)

I checked your data-bin file, and it seems lack ./data-bin/train-obj.h5py file.
how do you get train-obj.h5py? thanks

**Comment by LibertFan** [comment]
You can download the file in BaiduDisk.
