### ISSUE TITLE
checkpoint file

### ISSUE THREAD

**Issue by Xiang-yang-feng** [LibertFan/TCIC#2]
Hi:
  Recently,I'm doing a image caption project. The ideas you have mentioned in your paper do a lot help to me. Thanks to your work and ideas, I  think the problems I have met ,which should include "theme" concept in a specifc scenarios，can be solved.
  Would you mind share your checkpoint files of your module? I would appreciate it if you could do that.

  all the best !

**Comment by LibertFan** [comment]
I have uploaded the checkpoint to BaiduDisk.   https://pan.baidu.com/s/1PIsAxxPkrL3G0NkrSldPIQ      Code: 3dks
